---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: datawire
  namespace: flux-system
spec:
  interval: 24h
  url: https://app.getambassador.io
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: emissary-ingress
  namespace: flux-system
spec:
  dependsOn:
    - name: cilium
      namespace: flux-system
  interval: 30m
  targetNamespace: platform
  chart:
    spec:
      chart: emissary-ingress
      version: 8.12.2
      sourceRef:
        kind: HelmRepository
        name: datawire
        namespace: flux-system
      interval: 12h
      valuesFiles:
        - values.yaml