apiVersion: apps/v1
kind: Deployment
metadata:
  name: tcp-deployment
  labels:
    app: tcp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tcp
  template:
    metadata:
      labels:
        app: tcp
    spec:
      containers:
      - name: tcp-container
        image: busybox
        # This command runs a simple TCP listener on port 8080
        command: ["/bin/sh", "-c"]
        args:
        - while true; do echo -e "HTTP/1.1 200 OK\n\nTCP-OK" | nc -l -p 8080; done
        ports:
        - name: tcp
          containerPort: 8080
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: tcp-service
spec:
  selector:
    app: tcp
  ports:
    - name: tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP

# To test:
# kubectl run netcat-client --image=busybox --rm -it -- /bin/sh
# # Inside the debug pod
# nc -v tcp-service 8080
# nc -u -v tcp-service 8081

