---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-cluster-issuer
  namespace: platform
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: selfsigned-certs
  namespace: platform
spec:
  duration: 8760h # Valid for 1 year
  renewBefore: 720h # Renew 30 days before expiry
  privateKey:
    algorithm: RSA
    size: 2048
    rotationPolicy: Always
  secretName: selfsigned-tls # change this
  issuerRef:
    name: selfsigned-cluster-issuer # change this
    kind: ClusterIssuer
    group: cert-manager.io
  ipAddresses:
  - 172.18.1.100