apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpc-server
  template:
    metadata:
      labels:
        app: grpc-server
    spec:
      containers:
      - name: grpc-server
        image: appsecco/grpc-echo-server
        ports:
          - containerPort: 50051
---
apiVersion: v1
kind: Service
metadata:
  name: grpc-server
spec:
  selector:
    app: grpc-server
  ports:
    - port: 50051
      targetPort: 50051

# To test:
# kubectl port-forward svc/grpc-server 50051:50051
# grpcurl -plaintext localhost:50051 list
