apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-hello-deployment
  labels:
    app: grpc-hello
spec:
  replicas: 2
  selector:
    matchLabels:
      app: grpc-hello
  template:
    metadata:
      labels:
        app: grpc-hello
    spec:
      containers:
      - name: grpc-hello-server
        image: jonathanad/grpc-hello-world:v4
        ports:
        - containerPort: 50051
---
apiVersion: v1
kind: Service
metadata:
  name: grpc-hello-service
spec:
  selector:
    app: grpc-hello
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051
  type: ClusterIP

# To test:
# kubectl port-forward svc/grpc-server 50051:50051
# grpcurl -plaintext localhost:50051 list
