apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-hello-deployment
  labels:
    app: grpc-hello
spec:
  replicas: 2
  selector:
    matchLabels:
      app: grpc-hello
  template:
    metadata:
      labels:
        app: grpc-hello
    spec:
      containers:
      - name: grpc-hello-server
        image: jonathanad/grpc-hello-world:v4
        ports:
        - containerPort: 50051
        env: # <--- THIS SECTION IS ADDED
        - name: GRPC_SERVER_ADDRESS
          value: "0.0.0.0:50051"
---
apiVersion: v1
kind: Service
metadata:
  name: grpc-hello-service
spec:
  selector:
    app: grpc-hello
  ports:
    - protocol: TCP
      port: 80
      targetPort: 50051
  type: ClusterIP

# To test:
# kubectl port-forward service/grpc-hello-service 9090:80
# This command lists the services available
# grpcurl -plaintext localhost:9090 list

# # This command calls the SayHello method
# grpcurl -plaintext -d '{"name": "Kubernetes"}' localhost:9090 hello.Greeter/SayHello
