apiVersion: apps/v1
kind: Deployment
metadata:
  name: tcp-udp-deployment
  labels:
    app: tcp-udp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tcp-udp
  template:
    metadata:
      labels:
        app: tcp-udp
    spec:
      containers:
      - name: multi-protocol-server
        image: ealen/echo-server
        ports:
        - name: tcp
          containerPort: 8080
          protocol: TCP
        - name: udp
          containerPort: 8080
          protocol: UDP
        env:
        - name: TCP_PORT
          value: "8080"
        - name: UDP_PORT
          value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: tcp-udp-service
spec:
  selector:
    app: tcp-udp
  ports:
    - name: tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: udp
      protocol: UDP
      port: 8080
      targetPort: 8080
  type: ClusterIP

# To test:
# kubectl debug -it netcat-client --image=subfuzion/netcat -- /bin/sh
# # Inside the netcat-client pod
# nc -v tcp-udp-service 8080
# nc -u -v tcp-udp-service 8080

