apiVersion: apps/v1
kind: Deployment
metadata:
  name: dual-container-echo-deployment
  labels:
    app: dual-container-echo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dual-container-echo
  template:
    metadata:
      labels:
        app: dual-container-echo
    spec:
      containers:
      - name: tcp-echo-container
        image: jmalloc/echo-server
        ports:
        - name: tcp
          containerPort: 8080
          protocol: TCP

      - name: udp-echo-container
        image: jmalloc/echo-server
        args: ["--protocol=udp", "--port=8081"] # Tell this container to use UDP on a different port
        ports:
        - name: udp
          containerPort: 8081
          protocol: UDP
---
apiVersion: v1
kind: Service
metadata:
  name: dual-container-echo-service
spec:
  selector:
    app: dual-container-echo
  ports:
    - name: tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: udp
      protocol: UDP
      port: 8081
      targetPort: 8081
  type: ClusterIP

# To test:
# kubectl port-forward service/dual-container-echo-service 9090:8080
# nc localhost 9090
# kubectl run -it --rm netcat-client --image=subfuzion/netcat -- /bin/sh
# # Inside the netcat-client pod
# nc -uzv dual-container-echo-service 8081

