apiVersion: apps/v1
kind: Deployment
metadata:
  name: tcp-udp-deployment
  labels:
    app: tcp-udp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tcp-udp
  template:
    metadata:
      labels:
        app: tcp-udp
    spec:
      containers:
      - name: tcp-container
        image: jmalloc/echo-server
        # Explicitly set protocol and port
        args: ["--protocol=tcp", "--port=8080"]
        ports:
        - name: tcp
          containerPort: 8080
          protocol: TCP

      - name: udp-container
        image: jmalloc/echo-server
        # Explicitly set protocol and a DIFFERENT port
        args: ["--protocol=udp", "--port=8081"]
        ports:
        - name: udp
          containerPort: 8081
          protocol: UDP
---
apiVersion: v1
kind: Service
metadata:
  name: tcp-udp-service
spec:
  selector:
    app: tcp-udp
  ports:
    - name: tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: udp
      protocol: UDP
      port: 8081
      targetPort: 8081
  type: ClusterIP

# To test:
# kubectl run netcat-client --image=busybox --rm -it -- /bin/sh
# # Inside the debug pod
# nc -v multi-protocol-server 8080
# nc -u -v multi-protocol-server 8080

