apiVersion: apps/v1
kind: Deployment
metadata:
  name: ws-echo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ws-echo
  template:
    metadata:
      labels:
        app: ws-echo
    spec:
      containers:
      - name: echo-server
        image: ealen/echo-server
        ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: ws-echo
spec:
  selector:
    app: ws-echo
  ports:
    - port: 80
      targetPort: 80

# To test:
# kubectl port-forward svc/ws-echo 8081:80
# wscat -c ws://localhost:8081/ws
