---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: coder
  namespace: flux-system
spec:
  interval: 24h
  url: https://helm.coder.com/v2
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: coder
  namespace: flux-system
spec:
  interval: 30m
  chart:
    spec:
      chart: coder
      version: 2.24.1
      sourceRef:
        kind: HelmRepository
        name: coder
        namespace: flux-system
      interval: 12h
  values: {}