---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: coder
  namespace: flux-system
spec:
  interval: 24h
  url: https://helm.coder.com/v2
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: postgresql-bitnami
  namespace: flux-system
spec:
  interval: 24h
  url: oci://registry-1.docker.io/bitnamicharts/postgresql
  ref:
    semver: "^16.7.21"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: coder-postgresql
  namespace: flux-system
spec:
  interval: 30m
  targetNamespace: coder
  install:
    createNamespace: true
  chartRef:
    kind: OCIRepository
    name: postgresql-bitnami
    namespace: flux-system
  values:
    global:
      postgresql:
        postgresqlDatabase: coder
        postgresqlUsername: coder
        postgresqlPassword: changeme
    fullNameOverride: coder-postgresql
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: coder
  namespace: flux-system
spec:
  dependsOn:
    - name: postgresql
      namespace: flux-system
  interval: 30m
  targetNamespace: coder
  install:
    createNamespace: true
  chart:
    spec:
      chart: coder
      version: 2.24.1
      sourceRef:
        kind: HelmRepository
        name: coder
        namespace: flux-system
      interval: 12h
  values:
    coder:
      env:
      - name: CODER_PG_CONNECTION_URL
        value: "postgresql://coder:changeme@coder-postgresql:5432/coder?sslmode=disable"
      - name: CODER_AGENT_START_TIMEOUT
        value: "1800s"