---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: datawire
  namespace: platform
spec:
  interval: 24h
  url: https://app.getambassador.io
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: emissary-ingress
  namespace: platform
spec:
  dependsOn:
    - name: cilium
      namespace: platform
  interval: 30m
  chart:
    spec:
      chart: emissary-ingress
      version: 8.12.2
      sourceRef:
        kind: HelmRepository
        name: datawire
        namespace: platform
      interval: 12h
  valuesFile:
    - values.yaml