---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: envoy-gateway
  namespace: flux-system
spec:
  interval: 24h
  url: oci://docker.io/envoyproxy/gateway-helm
  ref:
    tag: v1.4.0
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: envoy-gateway
  namespace: flux-system
spec:
  dependsOn:
    - name: cilium
      namespace: flux-system
  interval: 30m
  targetNamespace: platform
  chart:
    spec:
      chart: eg
      version: v1.4.0
      sourceRef:
        kind: HelmRepository
        name: envoy-gateway
        namespace: flux-system
      interval: 12h
      valuesFiles:
        - values.yaml