---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cilium
  namespace: platform
spec:
  interval: 24h
  url: https://helm.cilium.io/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: emissary-ingress
  namespace: platform
spec:
  interval: 30m
  chart:
    spec:
      chart: cilium
      version: 1.16.5
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: platform
      interval: 12h
  valuesFile:
    - values.yaml