---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: <name>
  namespace: flux-system
spec:
  interval: 24h
  url: <repo-url>
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: <release-name>
  namespace: flux-system
spec:
  dependsOn:
    - name: <dependency-name>
      namespace: <dependency-namespace>
  interval: 30m
  chart:
    spec:
      targetNamespace: <target-namespace>
      chart: <chart-name>
      version: <chart-version>
      sourceRef:
        kind: HelmRepository
        name: <repo-name>
        namespace: flux-system
      interval: 12h
      valuesFiles:
        - values.yaml