---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 24h
  url: https://charts.jetstack.io
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  dependsOn:
    - name: cilium
      namespace: flux-system
  interval: 30m
  targetNamespace: platform
  chart:
    spec:
      chart: cert-manager
      version: 1.17.2
      sourceRef:
        kind: HelmRepository
        name: cert-manager
        namespace: flux-system
      interval: 12h
      valuesFiles:
        - values.yaml