---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: envoy-gateway
  namespace: flux-system
spec:
  interval: 24h
  url: oci://docker.io/envoyproxy/gateway-helm
  ref:
    semver: "^1.4.0"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: envoy-gateway
  namespace: flux-system
spec:
  dependsOn:
    - name: cilium
      namespace: flux-system
  interval: 30m
  targetNamespace: platform
  chartRef:
    kind: OCIRepository
    name: envoy-gateway
    namespace: flux-system
  values:
    service:
      loadBalancerIP: 172.18.1.100
    deployment:
      envoyGateway:
        resources:
          limits:
            cpu: 700m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
    hpa:
      enabled: true
    config:
      envoyGateway:
        logging:
          level:
            default: debug
