---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: envoy-gateway
  namespace: flux-system
spec:
  type: oci
  interval: 24h
  url: oci://docker.io/envoyproxy/gateway-helm
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: envoy-gateway
  namespace: flux-system
spec:
  dependsOn:
    - name: cilium
      namespace: flux-system
    - name: metallb
      namespace: flux-system
    - name: cert-manager
      namespace: flux-system
  interval: 30m
  targetNamespace: platform
  chart:
    spec:
      chart: envoy-gateway
      version: "1.4.0"
      sourceRef:
        kind: HelmRepository
        name: envoy-gateway
        namespace: flux-system
      interval: 12h
      valuesFiles:
        - values.yaml
    